---
route:
  group_by: [alertname, moniker]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: "nowhere"

  routes:
    - matchers:
        - alertname="ValidatorEntersGP"
      repeat_interval: 10m  # twice "for" cond in Mute alert
      receiver: "nowhere"

    - matchers:
        - alertname="ValidatorEntersGPMute"
      receiver: "nowhere" # alert exists for inhibition only

    - matchers:
        - alertname="ValidatorGPBump"
      receiver: "nowhere"

inhibit_rules:
  - source_matchers: [alertname="ValidatorEntersGPMute"]
    target_matchers: [alertname="ValidatorEntersGP"]
    equal: ["moniker"]

receivers:
  - name: "nowhere"
