---
name: Linters

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
  js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Generate missing source files
        run: yarn run typechain

      - name: Run linting
        run: yarn lint
